#!/usr/bin/env bash

set -euo pipefail

TARGET_FILE="${1:-infra/local/.env}"

mkdir -p "$(dirname "$TARGET_FILE")"

ask() {
  local prompt="$1"
  local default_value="${2:-}"
  local response

  if [[ -n "$default_value" ]]; then
    read -r -p "$prompt [$default_value]: " response
    echo "${response:-$default_value}"
  else
    read -r -p "$prompt: " response
    echo "$response"
  fi
}

ask_secret() {
  local prompt="$1"
  local response
  read -r -s -p "$prompt: " response
  echo
  echo "$response"
}

echo "Snowflake .env generator"
echo "Target file: $TARGET_FILE"
echo "Pattern: prod uses base names, dev uses *_DEV"
echo

default_account=""
default_user=""
default_role="ACCOUNTADMIN"
default_warehouse="WH_SENTINEL"
default_database="SENTINEL"
default_schema="PUBLIC"
default_region=""
default_app_env="dev"
default_organization=""

app_env="$(ask "APP_ENV (dev|prod)" "$default_app_env")"

snowflake_organization="$(ask "SNOWFLAKE_ORGANIZATION (optional; e.g. vvyellg)" "$default_organization")"
snowflake_account="$(ask "SNOWFLAKE_ACCOUNT (org-account or account locator; e.g. vvyellg-cr56839 or cr56839)" "$default_account")"
snowflake_user="$(ask "SNOWFLAKE_USER" "$default_user")"
snowflake_password="$(ask_secret "SNOWFLAKE_PASSWORD")"
snowflake_role="$(ask "SNOWFLAKE_ROLE (prod)" "$default_role")"
snowflake_warehouse="$(ask "SNOWFLAKE_WAREHOUSE (prod)" "$default_warehouse")"
snowflake_database="$(ask "SNOWFLAKE_DATABASE (prod)" "$default_database")"
snowflake_schema="$(ask "SNOWFLAKE_SCHEMA (prod)" "$default_schema")"
snowflake_region="$(ask "SNOWFLAKE_REGION (optional)" "$default_region")"

snowflake_role_dev="$(ask "SNOWFLAKE_ROLE_DEV (dev)" "$snowflake_role")"
snowflake_warehouse_dev="$(ask "SNOWFLAKE_WAREHOUSE_DEV (dev)" "${snowflake_warehouse}_DEV")"
snowflake_database_dev="$(ask "SNOWFLAKE_DATABASE_DEV (dev)" "${snowflake_database}_DEV")"
snowflake_schema_dev="$(ask "SNOWFLAKE_SCHEMA_DEV (dev)" "$snowflake_schema")"

cat > "$TARGET_FILE" <<EOF
# Generated by infra/local/scripts/generate-env.sh
APP_ENV=$app_env

SNOWFLAKE_ACCOUNT=$snowflake_account
SNOWFLAKE_ORGANIZATION=$snowflake_organization
SNOWFLAKE_USER=$snowflake_user
SNOWFLAKE_PASSWORD=$snowflake_password
SNOWFLAKE_ROLE=$snowflake_role
SNOWFLAKE_ROLE_DEV=$snowflake_role_dev
SNOWFLAKE_WAREHOUSE=$snowflake_warehouse
SNOWFLAKE_WAREHOUSE_DEV=$snowflake_warehouse_dev
SNOWFLAKE_DATABASE=$snowflake_database
SNOWFLAKE_DATABASE_DEV=$snowflake_database_dev
SNOWFLAKE_SCHEMA=$snowflake_schema
SNOWFLAKE_SCHEMA_DEV=$snowflake_schema_dev
SNOWFLAKE_REGION=$snowflake_region
EOF

echo
echo "Created $TARGET_FILE"
echo "Tip: keep this file out of version control."
