#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"
ENV_FILE="${ENV_FILE:-$PROJECT_ROOT/infra/local/.env}"
RUN_NOW="${RUN_NOW:-true}"

usage() {
  echo "Usage: bash infra/local/scripts/setup_step2_snowpark_ingestion.sh [--setup-only]"
}

for arg in "$@"; do
  case "$arg" in
    --setup-only)
      RUN_NOW="false"
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $arg"
      usage
      exit 1
      ;;
  esac
done

require_cmd() {
  local cmd="$1"
  if ! command -v "$cmd" >/dev/null 2>&1; then
    echo "Error: required command not found: $cmd"
    exit 1
  fi
}

if [[ ! -f "$ENV_FILE" ]]; then
  echo "Error: env file not found at $ENV_FILE"
  echo "Run: make env"
  exit 1
fi

set -a
# shellcheck disable=SC1090
source "$ENV_FILE"
set +a

require_cmd snowsql

APP_ENV_VALUE="${APP_ENV:-dev}"
if [[ "$APP_ENV_VALUE" != "dev" && "$APP_ENV_VALUE" != "prod" ]]; then
  echo "Error: APP_ENV must be dev or prod in $ENV_FILE"
  exit 1
fi

if [[ -z "${SNOWFLAKE_ACCOUNT:-}" || -z "${SNOWFLAKE_USER:-}" || -z "${SNOWFLAKE_PASSWORD:-}" ]]; then
  echo "Error: SNOWFLAKE_ACCOUNT, SNOWFLAKE_USER and SNOWFLAKE_PASSWORD are required in $ENV_FILE"
  exit 1
fi

if [[ "$APP_ENV_VALUE" == "dev" ]]; then
  SNOWFLAKE_DATABASE_VALUE="${SNOWFLAKE_DATABASE_DEV:-${SNOWFLAKE_DATABASE:-SENTINEL}_DEV}"
  SNOWFLAKE_WAREHOUSE_VALUE="${SNOWFLAKE_WAREHOUSE_DEV:-${SNOWFLAKE_WAREHOUSE:-WH_SENTINEL}_DEV}"
  SNOWFLAKE_ROLE_VALUE="${SNOWFLAKE_ROLE_DEV:-${SNOWFLAKE_ROLE:-ACCOUNTADMIN}}"
else
  SNOWFLAKE_DATABASE_VALUE="${SNOWFLAKE_DATABASE:-SENTINEL}"
  SNOWFLAKE_WAREHOUSE_VALUE="${SNOWFLAKE_WAREHOUSE:-WH_SENTINEL}"
  SNOWFLAKE_ROLE_VALUE="${SNOWFLAKE_ROLE:-ACCOUNTADMIN}"
fi

SNOWFLAKE_ACCOUNT_IDENTIFIER="$SNOWFLAKE_ACCOUNT"
SNOWFLAKE_ORG_VALUE="${SNOWFLAKE_ORGANIZATION:-${SNOWFLAKE_ORGANIZATION_NAME:-}}"
if [[ "$SNOWFLAKE_ACCOUNT_IDENTIFIER" != *"-"* ]] && [[ -n "$SNOWFLAKE_ORG_VALUE" ]]; then
  SNOWFLAKE_ACCOUNT_IDENTIFIER="${SNOWFLAKE_ORG_VALUE}-${SNOWFLAKE_ACCOUNT_IDENTIFIER}"
fi

TASK_NAME="${SNOWFLAKE_SNOWPARK_TASK_NAME:-INGEST_ACCOUNT_USAGE_TO_BRONZE_TASK}"
PROC_NAME="${SNOWFLAKE_SNOWPARK_PROC_NAME:-SP_INGEST_ACCOUNT_USAGE}"
STAGE_NAME="${SNOWFLAKE_STAGE_NAME:-ACCOUNT_USAGE_EXT_STAGE}"
FILE_FORMAT_NAME="${SNOWFLAKE_FILE_FORMAT_NAME:-FF_ACCOUNT_USAGE_PARQUET}"

echo "Setting up Step 2 Snowpark ingestion"
echo "Environment: $APP_ENV_VALUE"
echo "Database: $SNOWFLAKE_DATABASE_VALUE"
echo "Warehouse: $SNOWFLAKE_WAREHOUSE_VALUE"
echo "Role: $SNOWFLAKE_ROLE_VALUE"
echo "Procedure: BRONZE.$PROC_NAME"
echo "Task: BRONZE.$TASK_NAME"

export SNOWSQL_PWD="$SNOWFLAKE_PASSWORD"

SETUP_SQL=$(cat <<SQL
USE ROLE ${SNOWFLAKE_ROLE_VALUE};
CREATE DATABASE IF NOT EXISTS ${SNOWFLAKE_DATABASE_VALUE};
USE DATABASE ${SNOWFLAKE_DATABASE_VALUE};
CREATE SCHEMA IF NOT EXISTS BRONZE;
USE SCHEMA BRONZE;

CREATE OR REPLACE TABLE QUERY_HISTORY_RAW (
  QUERY_ID STRING,
  USER_NAME STRING,
  ROLE_NAME STRING,
  WAREHOUSE_NAME STRING,
  DATABASE_NAME STRING,
  SCHEMA_NAME STRING,
  QUERY_TYPE STRING,
  START_TIME TIMESTAMP_NTZ,
  END_TIME TIMESTAMP_NTZ,
  EXECUTION_STATUS STRING,
  ERROR_CODE STRING,
  ERROR_MESSAGE STRING,
  BYTES_SCANNED NUMBER,
  ROWS_PRODUCED NUMBER,
  CREDITS_USED_CLOUD_SERVICES FLOAT,
  TOTAL_ELAPSED_TIME NUMBER
);

CREATE OR REPLACE TABLE WAREHOUSE_METERING_RAW (
  START_TIME TIMESTAMP_NTZ,
  END_TIME TIMESTAMP_NTZ,
  WAREHOUSE_ID NUMBER,
  WAREHOUSE_NAME STRING,
  CREDITS_USED FLOAT,
  CREDITS_USED_COMPUTE FLOAT,
  CREDITS_USED_CLOUD_SERVICES FLOAT
);

CREATE OR REPLACE PROCEDURE ${PROC_NAME}()
RETURNS STRING
LANGUAGE PYTHON
RUNTIME_VERSION = '3.10'
PACKAGES = ('snowflake-snowpark-python')
HANDLER = 'run'
AS
\$\$
def run(session):
    copy_query_history = "COPY INTO ${SNOWFLAKE_DATABASE_VALUE}.BRONZE.QUERY_HISTORY_RAW FROM @${SNOWFLAKE_DATABASE_VALUE}.BRONZE.${STAGE_NAME}/query_history/ FILE_FORMAT = (FORMAT_NAME = ${SNOWFLAKE_DATABASE_VALUE}.BRONZE.${FILE_FORMAT_NAME}) MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE ON_ERROR = 'CONTINUE'"

    copy_warehouse_metering = "COPY INTO ${SNOWFLAKE_DATABASE_VALUE}.BRONZE.WAREHOUSE_METERING_RAW FROM @${SNOWFLAKE_DATABASE_VALUE}.BRONZE.${STAGE_NAME}/warehouse_metering/ FILE_FORMAT = (FORMAT_NAME = ${SNOWFLAKE_DATABASE_VALUE}.BRONZE.${FILE_FORMAT_NAME}) MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE ON_ERROR = 'CONTINUE'"

    session.sql(copy_query_history).collect()
    session.sql(copy_warehouse_metering).collect()
    return "Step 2 ingest completed."
\$\$;

CREATE OR REPLACE TASK ${TASK_NAME}
  WAREHOUSE = ${SNOWFLAKE_WAREHOUSE_VALUE}
  SCHEDULE = 'USING CRON 20 * * * * UTC'
AS
CALL ${SNOWFLAKE_DATABASE_VALUE}.BRONZE.${PROC_NAME}();

ALTER TASK ${TASK_NAME} RESUME;
SQL
)

snowsql -a "$SNOWFLAKE_ACCOUNT_IDENTIFIER" -u "$SNOWFLAKE_USER" -o exit_on_error=true -q "$SETUP_SQL" >/dev/null
echo "Snowpark procedure and scheduled task created/resumed."

if [[ "$RUN_NOW" == "true" ]]; then
  RUN_SQL=$(cat <<SQL
USE ROLE ${SNOWFLAKE_ROLE_VALUE};
CALL ${SNOWFLAKE_DATABASE_VALUE}.BRONZE.${PROC_NAME}();
SELECT COUNT(*) AS QUERY_HISTORY_RAW_ROWS FROM ${SNOWFLAKE_DATABASE_VALUE}.BRONZE.QUERY_HISTORY_RAW;
SELECT COUNT(*) AS WAREHOUSE_METERING_RAW_ROWS FROM ${SNOWFLAKE_DATABASE_VALUE}.BRONZE.WAREHOUSE_METERING_RAW;
SQL
)
  snowsql -a "$SNOWFLAKE_ACCOUNT_IDENTIFIER" -u "$SNOWFLAKE_USER" -o exit_on_error=true -q "$RUN_SQL"
  echo "Initial Step 2 ingest completed."
else
  echo "Setup completed. Skipped immediate run (--setup-only)."
fi
